### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by mmm0608** [hridayK/Detection-of-AI-generated-images#1]
Hi, 

Great work, do you have a requirements file for versions of TF and so on? I ran on the latest and found it was using some depreciated syntax.

**Comment by hridayK** [comment]
sure, will make requirements.txt and push it in sometime

**Comment by hridayK** [comment]
I have added `requirements.txt`, sorry for the late update.
https://github.com/hridayK/Detection-of-AI-generated-images/blob/main/requirements.txt
