### ISSUE TITLE
About the filter

### ISSUE THREAD

**Issue by Diverance** [hridayK/Detection-of-AI-generated-images#3]
Thanks for the reimplement of the paper!

In preprocessing/filter.py 307: 
``    img = np.array(cv2.cvtColor((apply_filter_a(src_copy) + apply_filter_b(src_copy) + apply_filter_c(src_copy) + \
            apply_filter_d(src_copy) + apply_filter_e(src_copy) + apply_filter_f(src_copy)), cv2.COLOR_RGB2GRAY)//8)

1) It seems that 'apply_filter_g' is missing. 

2) The sum of all filters is divided by 8, but there are 6 sets of filters from 'a' to 'f' ( or 7 sets if 'a' to 'g'). Maybe it should be divided by 7 ?

**Comment by hridayK** [comment]
thanks for pointing this out, I was getting errors while trying to train it. Will try to fix this as well #2 by next weekend 🤞

**Comment by breadxiexie** [comment]
so may the
"img = np.array（cv2.cvtColor（（apply_filter_a（src_copy） + apply_filter_b（src_copy） + apply_filter_c（src_copy） +
apply_filter_d（src_copy） + apply_filter_e（src_copy） + apply_filter_f（src_copy）+ apply_filter_g（src_copy））， cv2.COLOR_RGB2GRAY）//7)
be right?

**Comment by hridayK** [comment]
yes, pushing the changes... thanks for pointing this out

**Comment by hridayK** [comment]
I have pushed the changes @Diverance @breadxiexie , you can refer to the commit [74626013](https://github.com/hridayK/Detection-of-AI-generated-images/commit/74626013ebf366294a01e1a8cecab04482693aa3)
