### ISSUE TITLE
about pixel_fluctuation.ipynb mentioned in README

### ISSUE THREAD

**Issue by cheatthegod** [hridayK/Detection-of-AI-generated-images#4]
Hello, I would like to know where the pixel_fluctuation.ipynb is

**Comment by hridayK** [comment]
I removed that notebook in previous commits to reduce the number of files in the project (should have removed its mention from README.md as well), but it was essentially using `patch_generator.py` 's functions to generate the two images and post which all the filters were applied on the images to reach the contrast, the notebook was just a display of that. (just using the implementation of functions from the `preprocess` folder)

**Comment by hridayK** [comment]
I have added a [preprocessing_demo.ipynb](https://github.com/hridayK/Detection-of-AI-generated-images/blob/main/preprocessing_demo.ipynb), you can refer the file to see the application of preprocessing as replacement for for the previous file. I am closing the issue for, but do let me know if I can add any more references.
